### ISSUE TITLE
Can't climb indoors?

### ISSUE THREAD

**Issue by tomasdev** [quarantin/zomboid-ladders#11]
![image](https://user-images.githubusercontent.com/364033/166101851-ee9288b9-4f75-481a-9641-f9bafa453535.png)

What could have I done wrong that means my indoor ladder doesn't work? It's attached to a floor upstairs and on a wall.

**Comment by quarantin** [comment]
It's not your fault, I've seen similar issues when the ladder is placed in a corner. I don't know the reason though. I'll let you know if/when I find a solution.
