### ISSUE TITLE
LoadGridsquare usage cause MP slow map chunk loading

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/zomboid-ladders#16]
As topic, the looping in LoadGridsquare significantly slow down loading for map chunk in MP. This cause significant map loading performance for server.

**Comment by Poltergeistzx** [comment]
Possible workaround for performance. Need somebody to test it more though.
https://github.com/Poltergeistzx/zomboid-ladders

**Comment by quarantin** [comment]
@Poltergeistzx fixed this issue. The mod is no longer using the LoadGridsquare event.
