### ISSUE TITLE
NE Louisville fire station pole not functioning.

### ISSUE THREAD

**Issue by Arretu** [quarantin/zomboid-ladders#22]
The fire pole at [13709x1778](https://map.projectzomboid.com/#13709x1778x10207) seems to be non-functional.

**Comment by Poltergeistzx** [comment]
That's problem with building. The bottom pole has roof on top and the other one has no level above.

**Comment by quarantin** [comment]
> That's problem with building. The bottom pole has roof on top and the other one has no level above.

Indeed.
